<?php

namespace FormationsBundle\Repository;

/**
 * DomainesFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainesFormationRepository  extends \Doctrine\ORM\EntityRepository
{

}