<?php


namespace InterviewsBundle\Repository;
use Doctrine\ORM\Query;
use Doctrine\ORM\EntityRepository;


/**
 * EvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                "SELECT e
                FROM InterviewsBundle:Evaluation e Join e.refEntretien p Join p.offre o Join o.idCondidat u
                WHERE u.username LIKE :str or o.poste LIKE :str "
            )
            ->setParameter('str', '%'.$str.'%')

            ->getResult();
    }
}