<?php


namespace InterviewsBundle\Repository;
use Doctrine\ORM\Query;
use Doctrine\ORM\EntityRepository;


/**
 * InterviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterviewRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str,$id){
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p
                FROM InterviewsBundle:Interview p Join p.offre o
                WHERE (o.poste LIKE :str or p.dateEnt LIKE :str) and o.idEntreprise='$id' "
            )
            ->setParameter('str', '%'.$str.'%')

            ->getResult();
    }

    public function findEntitiesByString_c($str,$id){
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p
                FROM InterviewsBundle:Interview p Join p.offre o Join o.idEntreprise u
                WHERE (o.poste LIKE :str or p.dateEnt LIKE :str or u.username LIKE :str) and o.idCondidat='$id' "
            )
            ->setParameter('str', '%'.$str.'%')

            ->getResult();
    }

    public function testdate()
    {
        $em= $query=$this->getEntityManager();
        $RAW_QUERY = "UPDATE interview SET  etat = 2 WHERE date_ent > SYSDATE()";
        $statement=$em->getConnection()->prepare($RAW_QUERY);

        //  $statement->bindValue('idt',$id);
        $statement->execute();



    }


    public function testdate2()
    {
        $em= $query=$this->getEntityManager();
        $RAW_QUERY = "UPDATE interview SET  etat = 1 WHERE date_ent < SYSDATE()";
        $statement=$em->getConnection()->prepare($RAW_QUERY);

        //  $statement->bindValue('idt',$id);
        $statement->execute();



    }
}