<?php

namespace OffreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends \Doctrine\ORM\EntityRepository
{
        public function myfind($id) {
            $q = $this->getEntityManager()
            ->createQuery("select o from OffreBundle:Offres o where o.entreprise= :id")
            ->setParameter('id', $id);

            return $query = $q->getResult();
        }



}
