<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8sna2xy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8sna2xy/appProdProjectContainer.php') {
    touch(__DIR__.'/Container8sna2xy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container8sna2xy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container8sna2xy\appProdProjectContainer([
    'container.build_hash' => '8sna2xy',
    'container.build_id' => 'e27fb84b',
    'container.build_time' => 1575507507,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8sna2xy');
