<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA3nzoaa\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA3nzoaa/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerA3nzoaa.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerA3nzoaa\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerA3nzoaa\appProdProjectContainer([
    'container.build_hash' => 'A3nzoaa',
    'container.build_id' => 'dbfe51de',
    'container.build_time' => 1575479081,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA3nzoaa');
