<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOmxbvza\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOmxbvza/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOmxbvza.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOmxbvza\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOmxbvza\appProdProjectContainer([
    'container.build_hash' => 'Omxbvza',
    'container.build_id' => 'c57db909',
    'container.build_time' => 1575025456,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOmxbvza');
