<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Controller\DefaultController' shared autowired service.

return $this->services['AppBundle\\Controller\\DefaultController'] = new \AppBundle\Controller\DefaultController();
