<?php

namespace Reclamation1Bundle\Repository;

/**
 * Reclamation1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Reclamation1Repository extends \Doctrine\ORM\EntityRepository
{
}
