<?php

namespace Reclamation1Bundle\Repository;
use Reclamation1Bundle\Entity\Reclamation;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Doctrine\ORM\EntityManagerInterface;

/**
 * Reclamation1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Reclamation1Repository extends EntityRepository
{
    public function getBysubjectonly($subject)
    {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT r
                FROM Reclamation1Bundle:Reclamation r
                WHERE r.subject = :subject '
            )
            ->setParameter('subject', '%'.$subject.'%')

            ->getResult();
    }
    public function findEntitiesBysubject($str){

        return $this->getEntityManager()
            ->createQuery(
                'SELECT r
                FROM Reclamation1Bundle:Reclamation r
                WHERE r.subject LIKE :str
                GROUP BY r.subject  '
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}
