<?php

namespace ProjectBundle\Repository;

/**
 * showInvesstirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class showInvesstirRepository extends \Doctrine\ORM\EntityRepository
{
    public function afficherMesInvesstment($id)
    {
        $em= $query=$this->getEntityManager();
        $RAW_QUERY = "SELECT p.nom_projet,u.fullname,u.tel, i.montant,i.numcarteBancaire,i.date_invesstissement,c.nom,p.Image FROM investissement i JOIN projet p ON i.id_projet=p.id_projet JOIN users u ON i.id_invesstisseur=u.id JOIN categories c ON c.id=p.id_categorie WHERE i.id_invesstisseur=:id";

        $statement=$em->getConnection()->prepare($RAW_QUERY);
        $statement->bindValue('id',$id);
        $statement->execute();
        $result=$statement->fetchAll();

        return $result;

    }
    public function afficherMesProjetInvesstment($id)
    {
        $em= $query=$this->getEntityManager();
        $RAW_QUERY = "SELECT p.nom_projet,u.fullname,u.tel, i.montant,i.numcarteBancaire,i.date_invesstissement,c.nom,p.Image FROM investissement i JOIN projet p ON i.id_projet=p.id_projet JOIN users u ON i.id_invesstisseur=u.id JOIN categories c ON c.id=p.id_categorie WHERE  p.id_entreprise=:id";

        $statement=$em->getConnection()->prepare($RAW_QUERY);
        $statement->bindValue('id',$id);
        $statement->execute();
        $result=$statement->fetchAll();

        return $result;

    }








}
