<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBzjlohg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBzjlohg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBzjlohg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBzjlohg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBzjlohg\appDevDebugProjectContainer([
    'container.build_hash' => 'Bzjlohg',
    'container.build_id' => 'a1003f62',
    'container.build_time' => 1575188875,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBzjlohg');
