<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAb6ax22\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAb6ax22/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAb6ax22.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAb6ax22\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAb6ax22\appDevDebugProjectContainer([
    'container.build_hash' => 'Ab6ax22',
    'container.build_id' => 'e0f86db4',
    'container.build_time' => 1574984933,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAb6ax22');
