<?php

namespace Proxies\__CG__\Reclamation1Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Projet extends \Reclamation1Bundle\Entity\Projet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'idProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'nomProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'categorie', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'paye', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'votreFinance', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'nbreContributeur', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'montant', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'compteBancaire', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'duree', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'dateFinProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'dateDebutProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'adresseProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'telProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'nbreTeam', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'descriptionProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'emailProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'idEnterprise'];
        }

        return ['__isInitialized__', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'idProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'nomProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'categorie', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'paye', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'votreFinance', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'nbreContributeur', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'montant', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'compteBancaire', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'duree', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'dateFinProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'dateDebutProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'adresseProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'telProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'nbreTeam', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'descriptionProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'emailProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Projet' . "\0" . 'idEnterprise'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Projet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdProjet()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdProjet();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProjet', []);

        return parent::getIdProjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomProjet($nomProjet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomProjet', [$nomProjet]);

        return parent::setNomProjet($nomProjet);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomProjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomProjet', []);

        return parent::getNomProjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie($categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaye($paye)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaye', [$paye]);

        return parent::setPaye($paye);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaye()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaye', []);

        return parent::getPaye();
    }

    /**
     * {@inheritDoc}
     */
    public function setVotreFinance($votreFinance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVotreFinance', [$votreFinance]);

        return parent::setVotreFinance($votreFinance);
    }

    /**
     * {@inheritDoc}
     */
    public function getVotreFinance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVotreFinance', []);

        return parent::getVotreFinance();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbreContributeur($nbreContributeur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbreContributeur', [$nbreContributeur]);

        return parent::setNbreContributeur($nbreContributeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbreContributeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbreContributeur', []);

        return parent::getNbreContributeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontant($montant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontant', [$montant]);

        return parent::setMontant($montant);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontant', []);

        return parent::getMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompteBancaire($compteBancaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompteBancaire', [$compteBancaire]);

        return parent::setCompteBancaire($compteBancaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompteBancaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompteBancaire', []);

        return parent::getCompteBancaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuree($duree)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuree', [$duree]);

        return parent::setDuree($duree);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuree', []);

        return parent::getDuree();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFinProjet($dateFinProjet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFinProjet', [$dateFinProjet]);

        return parent::setDateFinProjet($dateFinProjet);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFinProjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFinProjet', []);

        return parent::getDateFinProjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebutProjet($dateDebutProjet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebutProjet', [$dateDebutProjet]);

        return parent::setDateDebutProjet($dateDebutProjet);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebutProjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebutProjet', []);

        return parent::getDateDebutProjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseProjet($adresseProjet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseProjet', [$adresseProjet]);

        return parent::setAdresseProjet($adresseProjet);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseProjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseProjet', []);

        return parent::getAdresseProjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelProjet($telProjet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelProjet', [$telProjet]);

        return parent::setTelProjet($telProjet);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelProjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelProjet', []);

        return parent::getTelProjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbreTeam($nbreTeam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbreTeam', [$nbreTeam]);

        return parent::setNbreTeam($nbreTeam);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbreTeam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbreTeam', []);

        return parent::getNbreTeam();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionProjet($descriptionProjet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionProjet', [$descriptionProjet]);

        return parent::setDescriptionProjet($descriptionProjet);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionProjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionProjet', []);

        return parent::getDescriptionProjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailProjet($emailProjet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailProjet', [$emailProjet]);

        return parent::setEmailProjet($emailProjet);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailProjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailProjet', []);

        return parent::getEmailProjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEnterprise($idEnterprise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEnterprise', [$idEnterprise]);

        return parent::setIdEnterprise($idEnterprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEnterprise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEnterprise', []);

        return parent::getIdEnterprise();
    }

}
