<?php

namespace Proxies\__CG__\Reclamation1Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Formations extends \Reclamation1Bundle\Entity\Formations implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'ref', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'nom', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'domaineId', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'description', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'duree', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'dateDebut', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'dateFin', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'horraires', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'prix', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'region', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'adresse', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'email', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'tel'];
        }

        return ['__isInitialized__', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'ref', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'nom', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'domaineId', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'description', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'duree', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'dateDebut', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'dateFin', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'horraires', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'prix', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'region', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'adresse', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'email', '' . "\0" . 'Reclamation1Bundle\\Entity\\Formations' . "\0" . 'tel'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Formations $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getRef()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getRef();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRef', []);

        return parent::getRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomaineId($domaineId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomaineId', [$domaineId]);

        return parent::setDomaineId($domaineId);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomaineId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomaineId', []);

        return parent::getDomaineId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuree($duree)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuree', [$duree]);

        return parent::setDuree($duree);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuree', []);

        return parent::getDuree();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebut($dateDebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebut', [$dateDebut]);

        return parent::setDateDebut($dateDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebut', []);

        return parent::getDateDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFin($dateFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFin', [$dateFin]);

        return parent::setDateFin($dateFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFin', []);

        return parent::getDateFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorraires($horraires)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorraires', [$horraires]);

        return parent::setHorraires($horraires);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorraires()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorraires', []);

        return parent::getHorraires();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegion($region)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegion', [$region]);

        return parent::setRegion($region);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegion', []);

        return parent::getRegion();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$tel]);

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

}
