<?php

namespace Proxies\__CG__\Reclamation1Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Investissement extends \Reclamation1Bundle\Entity\Investissement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Reclamation1Bundle\\Entity\\Investissement' . "\0" . 'idInvestissement', '' . "\0" . 'Reclamation1Bundle\\Entity\\Investissement' . "\0" . 'montant', '' . "\0" . 'Reclamation1Bundle\\Entity\\Investissement' . "\0" . 'numcartebancaire', '' . "\0" . 'Reclamation1Bundle\\Entity\\Investissement' . "\0" . 'idProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Investissement' . "\0" . 'idInvesstisseur'];
        }

        return ['__isInitialized__', '' . "\0" . 'Reclamation1Bundle\\Entity\\Investissement' . "\0" . 'idInvestissement', '' . "\0" . 'Reclamation1Bundle\\Entity\\Investissement' . "\0" . 'montant', '' . "\0" . 'Reclamation1Bundle\\Entity\\Investissement' . "\0" . 'numcartebancaire', '' . "\0" . 'Reclamation1Bundle\\Entity\\Investissement' . "\0" . 'idProjet', '' . "\0" . 'Reclamation1Bundle\\Entity\\Investissement' . "\0" . 'idInvesstisseur'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Investissement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdInvestissement()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdInvestissement();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdInvestissement', []);

        return parent::getIdInvestissement();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontant($montant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontant', [$montant]);

        return parent::setMontant($montant);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontant', []);

        return parent::getMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumcartebancaire($numcartebancaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumcartebancaire', [$numcartebancaire]);

        return parent::setNumcartebancaire($numcartebancaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumcartebancaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumcartebancaire', []);

        return parent::getNumcartebancaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProjet($idProjet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProjet', [$idProjet]);

        return parent::setIdProjet($idProjet);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProjet', []);

        return parent::getIdProjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdInvesstisseur($idInvesstisseur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdInvesstisseur', [$idInvesstisseur]);

        return parent::setIdInvesstisseur($idInvesstisseur);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdInvesstisseur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdInvesstisseur', []);

        return parent::getIdInvesstisseur();
    }

}
